<a href="https://colab.research.google.com/github/mac-raj/LeNetArchitecture/blob/main/LeNetArchitecture.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Data

In [1]:
import keras 

# import mnist data from keras 
from keras.datasets import mnist

# import layers 
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Dense,Flatten

# import sequential model
from keras.models import Sequential

**Loading Data**

In [2]:
(X_train,y_train),(X_test,y_test) = mnist.load_data()

# Data Preprocessing 

In [3]:
X_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [4]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [5]:
X_train.shape

(60000, 28, 28)

**Reshape**

In [6]:
# Peforming reshaping operation
X_train = X_train.reshape(X_train.shape[0], 28, 28, 1)
X_test = X_test.reshape(X_test.shape[0], 28, 28, 1)

In [7]:
X_train

array([[[[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        ...,

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]]],


       [[[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        ...,

        [[0],
         [0],
         [0],
         ...,
         [0],


In [8]:
X_train.shape

(60000, 28, 28, 1)

**Normalization**

In [9]:
X_train = X_train / 255
X_test = X_test / 255

**Label Encoding**

In [10]:
y_train = keras.utils.to_categorical(y_train, num_classes=10)
y_test = keras.utils.to_categorical(y_test, num_classes=10)

# LeNet Model Architecture

In [14]:
model = Sequential()

model.add(Conv2D(6, kernel_size=(5,5), activation='relu', input_shape=(28,28,1)))

model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(16, kernel_size=(5,5), activation='relu', input_shape =(10,10,1)))

model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Flatten())

model.add(Dense(120, activation='relu'))

model.add(Dense(84, activation='relu'))

model.add(Dense(10, activation='softmax'))

In [15]:
model.compile(loss=keras.metrics.categorical_crossentropy, optimizer=keras.optimizers.Adam(), metrics=['accuracy'])

In [18]:
model.fit(X_train, y_train, batch_size=128, epochs=20, verbose=1, validation_data=(X_test, y_test))

Epoch 1/20
469/469 [==============================] - 28s 58ms/step - loss: 0.3226 - accuracy: 0.9081 - val_loss: 0.1009 - val_accuracy: 0.9700
Epoch 2/20
469/469 [==============================] - 27s 57ms/step - loss: 0.0927 - accuracy: 0.9716 - val_loss: 0.0632 - val_accuracy: 0.9807
Epoch 3/20
469/469 [==============================] - 26s 55ms/step - loss: 0.0669 - accuracy: 0.9793 - val_loss: 0.0462 - val_accuracy: 0.9848
Epoch 4/20
469/469 [==============================] - 26s 55ms/step - loss: 0.0543 - accuracy: 0.9829 - val_loss: 0.0481 - val_accuracy: 0.9845
Epoch 5/20
469/469 [==============================] - 27s 57ms/step - loss: 0.0439 - accuracy: 0.9861 - val_loss: 0.0354 - val_accuracy: 0.9891
Epoch 6/20
469/469 [==============================] - 26s 56ms/step - loss: 0.0389 - accuracy: 0.9877 - val_loss: 0.0401 - val_accuracy: 0.9886
Epoch 7/20
469/469 [==============================] - 26s 55ms/step - loss: 0.0336 - accuracy: 0.9894 - val_loss: 0.0402 - val_accuracy:

In [19]:
score = model.evaluate(X_test, y_test)
print('Test Loss:', score[0])
print('Test accuracy:', score[1])

313/313 [==============================] - 3s 8ms/step - loss: 0.0555 - accuracy: 0.9865
Test Loss: 0.05549049749970436
Test accuracy: 0.9865000247955322
